import { Product } from "./types";

export const DEFAULT_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name: "Червоні Vans Sk8-Hi",
    description: "Високі замшеві кеди Vans червоного кольору",
    price: 1260,
    image: "/implants/photo_21_2026-06-17_12-43-23.jpg",
    category: "shoes",
    sizes: ["36", "37", "38", "39", "40"],
    tags: ["y2k", "street", "grunge"],
    stock: 12,
    riddickRating: "COLLECTION 2026",
    mannequinYOffset: 120,
    mannequinScale: 0.95
  },
  {
    id: "prod-2",
    name: "Синій лонгслів з коміром",
    description: "Облягаючий лонгслів синій з білим коміром",
    price: 590,
    image: "/implants/photo_1_2026-06-17_12-43-23.jpg",
    category: "top",
    sizes: ["S", "M", "L"],
    tags: ["y2k", "alt", "preppy"],
    stock: 15,
    riddickRating: "COLLECTION 2026",
    mannequinYOffset: 15,
    mannequinScale: 1.05
  },
  {
    id: "prod-3",
    name: "Блакитні кльош джинси",
    description: "Світло-блакитні джинси кльош з низькою посадкою",
    price: 970,
    image: "/implants/photo_2_2026-06-17_12-43-23.jpg",
    category: "bottom",
    sizes: ["S", "M", "L"],
    tags: ["y2k", "grunge", "street"],
    stock: 8,
    riddickRating: "COLLECTION 2026",
    mannequinYOffset: 65,
    mannequinScale: 1.0
  },
  {
    id: "prod-4",
    name: "Червоний лонгслів з мереживом",
    description: "Облягаючий червоний лонгслів з мереживним коміром",
    price: 630,
    image: "/implants/photo_3_2026-06-17_12-43-23.jpg",
    category: "top",
    sizes: ["S", "M", "L"],
    tags: ["gothic", "y2k", "alt"],
    stock: 14,
    riddickRating: "COLLECTION 2026",
    mannequinYOffset: 15,
    mannequinScale: 1.05
  },
  {
    id: "prod-5",
    name: "Бордовий Henley лонгслів",
    description: "Рубчастий лонгслів бордовий з ґудзиками",
    price: 610,
    image: "/implants/photo_4_2026-06-17_12-43-23.jpg",
    category: "top",
    sizes: ["S", "M", "L"],
    tags: ["gothic", "y2k"],
    stock: 11,
    riddickRating: "COLLECTION 2026",
    mannequinYOffset: 15,
    mannequinScale: 1.05
  },
  {
    id: "prod-6",
    name: "Оливковий лонгслів з мереживом",
    description: "Облягаючий оливковий топ з подвійним мереживом",
    price: 650,
    image: "/implants/photo_5_2026-06-17_12-43-23.jpg",
    category: "top",
    sizes: ["S", "M", "L"],
    tags: ["alt", "y2k", "grunge"],
    stock: 19,
    riddickRating: "COLLECTION 2026",
    mannequinYOffset: 15,
    mannequinScale: 1.05
  },
  {
    id: "prod-7",
    name: "Темно-синій Henley",
    description: "Облягаючий темно-синій лонгслів з ґудзиками",
    price: 590,
    image: "/implants/photo_6_2026-06-17_12-43-23.jpg",
    category: "top",
    sizes: ["S", "M", "L"],
    tags: ["y2k", "street"],
    stock: 13,
    riddickRating: "COLLECTION 2026",
    mannequinYOffset: 15,
    mannequinScale: 1.05
  },
  {
    id: "prod-8",
    name: "Червона блуза з рюшами",
    description: "Коротка червона блуза з рюшами та коротким рукавом",
    price: 770,
    image: "/implants/photo_7_2026-06-17_12-43-23.jpg",
    category: "top",
    sizes: ["S", "M", "L"],
    tags: ["y2k", "alt"],
    stock: 16,
    riddickRating: "COLLECTION 2026",
    mannequinYOffset: 15,
    mannequinScale: 1.05
  },
  {
    id: "prod-9",
    name: "Темно-сині кльош джинси",
    description: "Темно-сині джинси кльош з декоративними блискавками",
    price: 1060,
    image: "/implants/photo_8_2026-06-17_12-43-23.jpg",
    category: "bottom",
    sizes: ["S", "M", "L"],
    tags: ["y2k", "street", "grunge"],
    stock: 10,
    riddickRating: "COLLECTION 2026",
    mannequinYOffset: 65,
    mannequinScale: 1.0
  },
  {
    id: "prod-10",
    name: "Сині кльош джинси з потертостями",
    description: "Джинси кльош темно-сині з ефектом б/у",
    price: 990,
    image: "/implants/photo_9_2026-06-17_12-43-23.jpg",
    category: "bottom",
    sizes: ["S", "M", "L"],
    tags: ["y2k", "grunge"],
    stock: 12,
    riddickRating: "COLLECTION 2026",
    mannequinYOffset: 65,
    mannequinScale: 1.0
  },
  {
    id: "prod-11",
    name: "Джинси кльош з вишивкою",
    description: "Блакитні джинси кльош з золотою вишивкою на кишенях",
    price: 1100,
    image: "/implants/photo_10_2026-06-17_12-43-23.jpg",
    category: "bottom",
    sizes: ["S", "M", "L"],
    tags: ["y2k", "street"],
    stock: 9,
    riddickRating: "COLLECTION 2026",
    mannequinYOffset: 65,
    mannequinScale: 1.0
  },
  {
    id: "prod-12",
    name: "Чорні Adidas Samba",
    description: "Класичні чорні кеди Adidas Samba",
    price: 1530,
    image: "/implants/photo_11_2026-06-17_12-43-23.jpg",
    category: "shoes",
    sizes: ["37", "38", "39", "40", "41"],
    tags: ["street", "grunge"],
    stock: 15,
    riddickRating: "COLLECTION 2026",
    mannequinYOffset: 120,
    mannequinScale: 0.95
  },
  {
    id: "prod-13",
    name: "Джинсові шорти з низькою посадкою",
    description: "Темні джинсові мікрошорти з низькою талією",
    price: 590,
    image: "/implants/photo_12_2026-06-17_12-43-23.jpg",
    category: "bottom",
    sizes: ["S", "M", "L"],
    tags: ["y2k", "grunge"],
    stock: 22,
    riddickRating: "COLLECTION 2026",
    mannequinYOffset: 65,
    mannequinScale: 1.0
  },
  {
    id: "prod-14",
    name: "Світлі джинсові шорти",
    description: "Джинсові шорти з потертостями та рваними краями",
    price: 560,
    image: "/implants/photo_13_2026-06-17_12-43-23.jpg",
    category: "bottom",
    sizes: ["S", "M", "L"],
    tags: ["y2k", "street"],
    stock: 17,
    riddickRating: "COLLECTION 2026",
    mannequinYOffset: 65,
    mannequinScale: 1.0
  },
  {
    id: "prod-15",
    name: "Бордовий в'язаний светр",
    description: "В'язаний светр бордовий з косами та мереживом",
    price: 900,
    image: "/implants/photo_14_2026-06-17_12-43-23.jpg",
    category: "top",
    sizes: ["S", "M", "L"],
    tags: ["gothic", "grunge", "alt"],
    stock: 16,
    riddickRating: "COLLECTION 2026",
    mannequinYOffset: 15,
    mannequinScale: 1.05
  },
  {
    id: "prod-16",
    name: "Коричнева парка Abercrombie",
    description: "Парка з хутряним капюшоном Abercrombie & Fitch",
    price: 1930,
    image: "/implants/photo_15_2026-06-17_12-43-23.jpg",
    category: "outerwear",
    sizes: ["S", "M", "L"],
    tags: ["grunge", "street"],
    stock: 5,
    riddickRating: "COLLECTION 2026",
    mannequinYOffset: -10,
    mannequinScale: 1.15
  },
  {
    id: "prod-17",
    name: "Чорні кльош штани",
    description: "Чорні штани кльош з низькою посадкою",
    price: 930,
    image: "/implants/photo_16_2026-06-17_12-43-23.jpg",
    category: "bottom",
    sizes: ["S", "M", "L"],
    tags: ["gothic", "street", "y2k"],
    stock: 14,
    riddickRating: "COLLECTION 2026",
    mannequinYOffset: 65,
    mannequinScale: 1.0
  },
  {
    id: "prod-18",
    name: "Чорна пуховка з хутром",
    description: "Чорна стьобана пуховка з великим хутряним капюшоном",
    price: 1770,
    image: "/implants/photo_17_2026-06-17_12-43-23.jpg",
    category: "outerwear",
    sizes: ["S", "M", "L"],
    tags: ["gothic", "street"],
    stock: 6,
    riddickRating: "COLLECTION 2026",
    mannequinYOffset: -10,
    mannequinScale: 1.15
  },
  {
    id: "prod-19",
    name: "Смугастий худі Hollister",
    description: "В'язаний худі в сіро-чорну смужку з капюшоном",
    price: 830,
    image: "/implants/photo_18_2026-06-17_12-43-23.jpg",
    category: "top",
    sizes: ["S", "M", "L"],
    tags: ["y2k", "grunge"],
    stock: 12,
    riddickRating: "COLLECTION 2026",
    mannequinYOffset: 15,
    mannequinScale: 1.05
  },
  {
    id: "prod-20",
    name: "Коричневі Skechers",
    description: "Замшеві кросівки Skechers коричневого кольору",
    price: 1130,
    image: "/implants/photo_19_2026-06-17_12-43-23.jpg",
    category: "shoes",
    sizes: ["36", "37", "38", "39", "40"],
    tags: ["street", "grunge"],
    stock: 9,
    riddickRating: "COLLECTION 2026",
    mannequinYOffset: 120,
    mannequinScale: 0.95
  },
  {
    id: "prod-21",
    name: "Коричневі платформні чоботи",
    description: "Чорні шкіряні чоботи на масивній платформі з блискавкою",
    price: 1860,
    image: "/implants/photo_20_2026-06-17_12-43-23.jpg",
    category: "shoes",
    sizes: ["36", "37", "38", "39"],
    tags: ["gothic", "alt"],
    stock: 8,
    riddickRating: "COLLECTION 2026",
    mannequinYOffset: 120,
    mannequinScale: 0.95
  }
];
